name: getfit
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  chat_gpt_sdk: ^2.2.5
  cloud_firestore: ^4.13.3
  dash_chat_2: ^0.0.19
  firebase_storage: ^11.5.3
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_messaging: ^14.7.6
  firebase_ui_auth: ^1.10.0
  flutter:
    sdk: flutter
  http: ^1.1.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  pdf: ^3.10.6
  flutter_markdown: ^0.6.18+2
  markdown: ^7.1.1
  printing: ^5.11.1
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications: ^16.2.0
  flutter_switch: ^0.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.0.7
  hive_generator: ^2.0.1
  analyzer: 6.2.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"

flutter:
  uses-material-design: true
